# Generated by Django 3.1 on 2020-09-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0002_subcategory_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstockitem',
            name='status',
            field=models.CharField(default='Normal', max_length=40),
        ),
    ]
