# Generated by Django 3.1 on 2020-09-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0003_addstockitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstockitem',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
    ]
