# Generated by Django 3.1 on 2020-09-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0005_auto_20200930_1736'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addstockitem',
            unique_together={('cat', 'subcat')},
        ),
    ]
