# Generated by Django 3.1 on 2020-09-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0006_auto_20200930_1737'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addstockitem',
            unique_together=set(),
        ),
    ]
