# Generated by Django 3.1 on 2020-09-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0007_auto_20200930_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstockitem',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='addstockitem',
            unique_together={('cat', 'subcat', 'name')},
        ),
    ]
