# Generated by Django 3.1 on 2020-09-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0009_auto_20200930_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-date_created']},
        ),
    ]
