# Generated by Django 3.1 on 2020-10-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0011_category_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstockitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
