# Generated by Django 3.1 on 2020-10-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0012_addstockitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstockitem',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
