# Generated by Django 3.1 on 2020-09-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientsmanagement', '0003_auto_20200912_0225'),
        ('ordermanagement', '0002_auto_20200912_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientsmanagement.client'),
        ),
    ]
