# Generated by Django 3.1 on 2020-09-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0003_auto_20200912_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createorder',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='createorder',
            name='urgency_level',
            field=models.CharField(default='Normal', max_length=30),
        ),
    ]
