# Generated by Django 3.1 on 2020-10-01 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0004_auto_20200928_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createorder',
            options={'ordering': ['-date_ordered']},
        ),
        migrations.AlterField(
            model_name='createorder',
            name='date_ordered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
