# Generated by Django 3.1 on 2020-10-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0005_auto_20201001_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='createorder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
