# Generated by Django 3.1 on 2020-10-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0006_createorder_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='createorder',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
