# Generated by Django 3.1 on 2020-10-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0007_createorder_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createorder',
            old_name='quantity',
            new_name='ordered_qty',
        ),
    ]
