# Generated by Django 3.1 on 2020-10-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0008_auto_20201017_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='createorder',
            name='delivered_qty',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
