# Generated by Django 3.1 on 2020-09-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsmanagement', '0002_remove_client_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=60),
        ),
    ]
