# Generated by Django 3.1 on 2020-09-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientsmanagement', '0003_auto_20200912_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
