# Generated by Django 3.1 on 2020-09-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsmanagement', '0004_remove_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(default='No address provided', max_length=200),
        ),
    ]
