# Generated by Django 3.1 on 2020-09-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsmanagement', '0005_auto_20200922_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(default='Not available', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='Not available', max_length=60),
        ),
    ]
