# Generated by Django 3.1 on 2020-10-01 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientsmanagement', '0006_auto_20200922_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='client',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='hospital_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
