# Generated by Django 3.1 on 2020-10-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientsmanagement', '0007_auto_20201001_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='location',
        ),
    ]
