# Generated by Django 3.1 on 2020-09-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitytracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytracker',
            name='bg_color',
            field=models.CharField(default='bg-yellow', max_length=10),
        ),
    ]
