# Generated by Django 3.1 on 2020-09-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitytracker', '0003_auto_20200928_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytracker',
            name='bg_color',
            field=models.CharField(default='bg-yellow', max_length=16),
        ),
        migrations.AlterField(
            model_name='activitytracker',
            name='activity_type',
            field=models.CharField(default='General', max_length=16),
        ),
    ]
