# Generated by Django 3.1 on 2020-10-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitytracker', '0004_auto_20200929_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytracker',
            name='bg_color',
        ),
    ]
