# Generated by Django 3.1 on 2020-10-02 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activitytracker', '0005_remove_activitytracker_bg_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytracker',
            options={'ordering': ['-activity_date']},
        ),
        migrations.AlterField(
            model_name='activitytracker',
            name='activity_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
